timezone: Europe/Berlin
defaults:  
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
future: false
kramdown:
  auto_ids: false